# Site settings
title: Personal Site of Christian Vervoorts
tag_text: Christian Vervoorts
description: Personal Website of Christian Vervoorts

# Build settings
markdown: kramdown
exclude: ["README.md", "Gemfile", "LICENSE", "Gemfile.lock"]
sass:
  style: compressed
